### PR TITLE
Patch/filter cleanup

### LINKED ISSUE #2: Remove `organ` filter
Remove filter for now given that it doesn't match data we have/isn't the most prioritized attribute to search by.

### LINKED ISSUE #56: Fix filtering for Gender/Sex
We do have values here, it looks like it's just a matter of looking at the ETL and final data structure to get filter serviced.

### PR DESCRIPTION
**Pull request by anngvu**
@inodb main reviewer, @cconrad8 for awareness

- Resolve `Gender` filter (most of data provided uses `Sex`, and the data model uses `Sex`). There are a couple places where this is is NA because it was not originally provided (because it was so obvious, or we're still waiting on final clinical data), but these should be relatively to confirm in the publication or get directly pretty soon.
- A couple of change ideas from #57 that made sense to include here (I think that PR included 4-5 conceptual changes, so for the remaining 2-3 ideas, potentially @cconrad8 could followup with a couple of smaller stabs at them)
  - Remove organ and country filters
  - Correct yet another HTAN id attribute

### CODE REVIEW

**Comment by cconrad8** [comment]
@anngvu any idea why records wouldn't be displayed here?

**Comment by anngvu** [comment]
@cconrad8 Moved this to draft to debug. Works on local dev after clearing cache, so I think this is some nuanced Vercel issue.
image

**Comment by onursumer** [comment]
Seems like the `processed_syn_data.json` is missing on the vercel instance

image

**Comment by anngvu** [comment]
Is it not running `gunzip` properly?

**Comment by cconrad8** [comment]
@anngvu Oh wait i think it's good now...I think I might have messed something up when I was doing stuff last week
the build command was set to next build

this is the picture of what I just switched it off to and it works:

image

**Comment by anngvu** [comment]
@cconrad8 Great, glad you remembered and figured it out! 👍🏼 😅  Really thought it was a weird caching issue.

**Review by cconrad8 — APPROVED** [review]

**Pull request merged**
